Fix an issue with the From header
Doranwen reported an issue with an pg4 where the sender crashed in email/_header_value_parser.py
with AttributeError: 'str' object has no attribute 'token_type'

Use an email.header.Header object to cleanup to From header.
The generated header is still wrong (ie From: .Some One <Some_One_uid96@yahoogroups.in_ valid>)
but the code doesn't crash anymore.

Still need to know why the email is broken;